name: orthophoniste
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_fonts: ^1.1.2
  flutter:
    sdk: flutter
  flutter_tts:


  get_it: ^3.0.3
  http: ^0.12.2
  audioplayers: ^0.17.4
  font_awesome_flutter: ^8.11.0
  shared_preferences: 0.5.12
  condition: ^0.0.7
  rflutter_alert: ^1.0.3
  auto_size_text: ^2.1.0
  url_launcher: ^5.4.5
  package_info: ^0.4.0+17
  share: ^0.6.4
  page_transition: ^1.1.5
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.7
  intl: ^0.16.1
  flutter_linkify: ^3.1.2
  soundpool: ^1.1.3

  frideos:
  speech_to_text: ^3.2.0
  highlight_text: ^0.7.2
  avatar_glow: ^1.2.0
  flutter_text_to_speech: ^3.0.7
  flutter_facebook_login: ^3.0.0

  flutter_neumorphic: ^3.0.3
  lottie: ^0.7.0+1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1


  #get: ^3.24.0
  #websafe_svg: ^1.1.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.0+2
  build_runner: ^1.9.0
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9

#flutter_icons:
  #android: "ic_launcher"
  #ios: false
  #image_path: "images/virus.png"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


flutter_native_splash:
  image: "images/virus.png"
  color: "FFFFFF"
  fill: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/
    - sounds/
    - assets/images_beg/
    - assets/icons/logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/Cairo-Black.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono-Bold.ttf
    - family: Stolzl
      fonts:
        - asset: assets/fonts/StolzlMedium.ttf

  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages